dependencies:
  - python=3
  - scipy=0.19.1
  - matplotlib=2.0.2
  - pandas=0.20.2
  - keras=2.0.2
  - tensorflow=1.1.0
  - theano=0.9.0
  - scikit-learn=0.18.2
  - pip=9.0.1
  - seaborn=0.7.1  
  - pip:
    - xgboost==0.6a2
