dependencies:
  - python=3
  - numpy=1.13.0
  - scipy=0.19.1
  - matplotlib=2.0.2
  - seaborn=0.7.1
  - pandas=0.20.2
  - keras=2.0.3
  - tensorflow=1.2.1
  - theano=0.9.0
  - scikit-learn=0.18.2
  - pip=9.0.1
  - pip:
    - xgboost==0.6a2